#!/bin/ksh

# ICON
#
# ------------------------------------------
# Copyright (C) 2004-2024, DWD, MPI-M, DKRZ, KIT, ETH, MeteoSwiss
# Contact information: icon-model.org
# See AUTHORS.TXT for a list of authors
# See LICENSES/ for license information
# SPDX-License-Identifier: BSD-3-Clause
# ------------------------------------------

inputfile=$1
outputfile=$2

callfolder=$(dirname $0)
here=$(pwd)
srciptfolder=$here/$callfolder

python $srciptfolder/check_style.py -i $inputfile $outputfile
if [ $? -ne 0 ];  then
   echo "check_style.py returned an Error. File $filename is unchanged."
fi




