DATA: '/work/gg0302/g260122/data/icon/trang'
DNICON: '/work/gg0302/g260122/data/icon/trang/icon_grid_ocean.nc'
IFILE: 0              # 0: use DNINP, 1: generate file name with INTAG
IOUT: 0               # 0: use DNOUT, 1: generate file name with PLTAG and var.name
DNWEI: 'w_riv2oce.nc'  # Weight file in DATA
DNINP: 'hd_sent.nc'   # Sending array on src grid, e.g. LSM or HD river mouths + receiving ocean boxes, or dis.nc
DNOUT: 'hd_to_icon_mapped'     # currently not generated for IWORK=2
IWORK: 2         # 1: 1D -> 2D mapping, e.g. use weight15.nc
#                  2: 2D -> 1D mapping, e.g. use weight11.nc or w_riv2oce.nc
IGRID: 0         # Target Grid: 0 = global 0.5°, 2=euro5min

