DATA: '/work/gg0302/g260122/data/icon/trang'
DPLOT: '/scratch/g/g260122/tmp/plot'
DNICON: '/work/gg0302/g260122/data/icon/trang/icon_grid_atmos.nc'
IFILE: 0              # 0: use DNINP, 1: generate file name with INTAG
IOUT: 0               # 0: use DNOUT, 1: generate file name with PLTAG and var.name
DNINP: 'w_atm2riv.nc'
DNOUT: 'icon_to_hd_weights_trang_r2b4'
IWORK: 2         # 1: Read src_address and plot hd_to_ICON, Use: weight11.nc
#                  2: read dst_address and plot HD_from_ICON, Use: weight15.nc
PLTAG: 'hd_from_icon_r2b4'
IREGION: 0       # Region no., 0 = globe, 10=euro5min
IDOMAIN: 0       # Domain: 0 = global 0.5°, 2=euro5min
XMIN: 0          # Minimum value for color range
XMAX: 1          # Maximum value for color range
XLOW: 0          # Values of XLOW and below are masked.
XMISS: -9999     # Missing Value
NCOL: 10         # Number of colors
ICOLTYP: 1       # Colormap, 0 = jet, 1=jet_r, 5=r-b, 6=b-r
LINTER: False    # Interactive run: no/yes
