#!/bin/bash

# ICON
#
# ------------------------------------------
# Copyright (C) 2004-2024, DWD, MPI-M, DKRZ, KIT, ETH, MeteoSwiss
# Contact information: icon-model.org
# See AUTHORS.TXT for a list of authors
# See LICENSES/ for license information
# SPDX-License-Identifier: BSD-3-Clause
# ------------------------------------------

set -eu

MY_DIR=$(cd "$(dirname "$0")"; pwd)
ICON_DIR=$(cd "${MY_DIR}/../.."; pwd)

if [ ! -z "${BB_NAME-}" ]; then
  set -x

  set MPI_LAUNCH='srun -A mh0156 -p compute -N 1 -t 2'
else
  # Setting MPI_LAUNCH to an empty string is not the same as not setting it at
  # all for the configure script of YAC. With the following, we make sure that
  # we do not pass any additional arguments:
  set dummy; shift
fi

${ICON_DIR}/config/dkrz/levante.nag --disable-openmp --enable-waves --disable-delayed-config "$@"

if [ ! -z "${BB_NAME-}" ] ; then
  MAKE_PROCS=22
else
  MAKE_PROCS=8
fi

make -j ${MAKE_PROCS}

if [ ! -z "${BB_NAME-}" ] ; then
  "${ICON_DIR}/scripts/buildbot_scripts/build_checks/check_depgen_warnings.sh"
  "${ICON_DIR}/scripts/buildbot_scripts/build_checks/check_remake.sh"
  "${ICON_DIR}/scripts/buildbot_scripts/build_checks/check_git_untracked.sh"
fi
