#!/bin/bash

# ICON
#
# ------------------------------------------
# Copyright (C) 2004-2024, DWD, MPI-M, DKRZ, KIT, ETH, MeteoSwiss
# Contact information: icon-model.org
# See AUTHORS.TXT for a list of authors
# See LICENSES/ for license information
# SPDX-License-Identifier: BSD-3-Clause
# ------------------------------------------

set -eu

MY_DIR=$(cd "$(dirname "$0")"; pwd)
ICON_DIR=$(cd "${MY_DIR}/../.."; pwd)

if [ ! -z "${BB_NAME-}" ] ; then
  MAKE_PROCS=22
else
  MAKE_PROCS=8
fi

${ICON_DIR}/config/csc/exec.lumi.container.cce bash -i - <<EOF
set -eu
${ICON_DIR}/config/csc/lumi.cpu.cce
make -j ${MAKE_PROCS} V=1
EOF
