#!/bin/bash

# ICON
#
# ------------------------------------------
# Copyright (C) 2004-2024, DWD, MPI-M, DKRZ, KIT, ETH, MeteoSwiss
# Contact information: icon-model.org
# See AUTHORS.TXT for a list of authors
# See LICENSES/ for license information
# SPDX-License-Identifier: BSD-3-Clause
# ------------------------------------------

set -e
set -x

# set required environment variables
export MODULESHOME="/usr/share/Modules"

# this wrapper needs to build two ICON binaries
MY_DIR=$(cd "$(dirname "$0")"; pwd)
ICON_DIR=$(cd "${MY_DIR}/../.."; pwd)

# create vector engine binary
# ${ICON_DIR}/config/dwd/rcl.VE.nfort-3.1.0_ftrace_oes --prefix=${PWD}/vector
${ICON_DIR}/config/dwd/rcl.VE.nfort-3.1.0_oes --prefix=${PWD}/vector

MAKE_PROCS=14
make -j ${MAKE_PROCS}
make install

make distclean

# create vector host binary
${ICON_DIR}/config/dwd/rcl.VH.gcc-9.1.0_oes --prefix=${PWD}/host
MAKE_PROCS=14
make -j ${MAKE_PROCS}
make install

VECTOR_BINARY="${PWD}/vector/bin/icon"
HOST_BINARY="${PWD}/host/bin/icon"

set +e
find "${PWD}/vector" "${PWD}/host"
file "$VECTOR_BINARY" "$HOST_BINARY"
