#! /usr/bin/env python

# ICON
#
# ---------------------------------------------------------------
# Copyright (C) 2004-2024, DWD, MPI-M, DKRZ, KIT, ETH, MeteoSwiss
# Contact information: icon-model.org
# See AUTHORS.TXT for a list of authors
# See LICENSES/ for license information
# SPDX-License-Identifier: BSD-3-Clause
# ---------------------------------------------------------------

from fileinput import input
from datetime import datetime

for line in input():
    print(datetime.now().strftime("%FT%T.%f")[:-3], line,
          sep=': ', end='', flush=True)
