# Copyright (c) 2024 The YAC Authors
#
# SPDX-License-Identifier: CC-BY-4.0

predef:
  ocn2atm: &ocn2atm
    src_component: ICON-O
    src_grid: grid1
    tgt_component: ICON-A
    tgt_grid: grid3
  atm2ocn: &atm2ocn
    src_component: ICON-A
    src_grid: grid3
    tgt_component: ICON-O

debug:
  global_config:
    def_comp: test_couple_config_def_comp.yaml
    sync_def:
      filename: test_couple_config_sync_def.json
      filetype: json
      include_definitions: false
    enddef:
      filename: test_couple_config_enddef.yaml
      include_definitions: true
  output_grids:
    - grid_name: grid1
      file_name: debug_grid.nc

start_date: 2008-03-09T16:05:07
end_date: 2008-03-10T16:05:07
timestep_unit: second
coupling:
  - <<: *ocn2atm
    coupling_period: 10
    src_lag: 0
    tgt_lag: 4
    weight_file_name: weights1.nc
    mapping_side: source
    interpolation:
      - nnn:
          n: 16
      - average
      - conservative
      - bernstein_bezier
      - user_file:
         filename: weights.nc
      - fixed:
         user_value: -1.0
    field: sea_surface_temperature
    src_mask_name: src_sst_mask
    tgt_mask_name: tgt_sst_mask
  - <<: *atm2ocn
    tgt_grid: grid1
    coupling_period: 20
    time_reduction: accumulate
    src_lag: 1
    tgt_lag: 3
    scale_factor: 10.0
    interpolation:
      - average:
          weighted: distance_weighted
          partial_coverage: TRUE
      - nnn:
          n: 2
          weighted: distance_weighted
      - conservative:
          order: 2
          enforced_conservation: true
          partial_coverage: true
          normalisation: fracarea
    field: wind_speed
    src_mask_names: ['src_wind_mask1', 'src_wind_mask2', 'src_wind_mask3']
  - <<: *ocn2atm
    coupling_period: 30
    time_reduction: average
    src_lag: 2
    tgt_lag: 2
    weight_file_name: weights3.nc
    mapping_side: target
    scale_summand: -1
    interpolation:
      - check
      - check:
          constructor_key: check_constructor
      - check:
          do_search_key: check_do_search
      - check:
          constructor_key: check_constructor
          do_search_key: check_do_search
      - rbf:
          n: 4
          rbf_kernel: gauss_kernel
    field: water_flux_into_sea_water
  - <<: *atm2ocn
    tgt_grid: grid2
    coupling_period: 40
    time_reduction: minimum
    src_lag: 3
    tgt_lag: 1
    mapping_side: target
    scale_factor: 0.5
    scale_summand: -0.5
    interpolation:
      - nnn:
          n: 8
          weighted: gauss_weighted
          max_search_distance: 90.0
          gauss_scale: 0.2
      - source_to_target_map:
          spread_distance: 5.0
          weighted: distance_weighted
          src_sphere_radius: 1.0
          tgt_sphere_radius: 2.0
      - ncc:
          weighted: distance_weighted
          partial_coverage: TRUE
      - rbf:
          n: 4
          max_search_distance: 90.0
          rbf_kernel: gauss_kernel
    field: grid_eastward_wind
  - <<: *ocn2atm
    src_grid: grid2
    coupling_period: 50
    time_reduction: maximum
    src_lag: 4
    tgt_lag: 0
    weight_file_name: weights5.nc
    mapping_side: source
    interpolation:
      - creep:
          creep_distance: 5
      - user_callback:
          func_compute_weights: compute_weights
      - fixed:
          user_value: -2.0
    field: grid_northward_wind
  - src_component: ICON-O
    src_grid: grid2
    tgt_component: DUMMY
    tgt_grid: grid4
    coupling_period: 50
    time_reduction: maximum
    src_lag: 4
    tgt_lag: 0
    weight_file_name: weights6.nc
    mapping_side: source
    interpolation:
      - creep:
          creep_distance: -1
      - user_callback:
          func_compute_weights: compute_weights
      - fixed:
          user_value: -1.0
    field: grid_northward_wind
  - src_component: src_comp
    src_grid: [src_grid_1, src_grid_2]
    tgt_component: tgt_comp
    tgt_grid: [tgt_grid_1, tgt_grid_2]
    coupling_period: 1
    interpolation:
      - fixed:
          user_value: -1.0
    field: multi_grid_field
