#!/bin/ksh

# ICON
#
# ---------------------------------------------------------------
# Copyright (C) 2004-2024, DWD, MPI-M, DKRZ, KIT, ETH, MeteoSwiss
# Contact information: icon-model.org
# See AUTHORS.TXT for a list of authors
# See LICENSES/ for license information
# SPDX-License-Identifier: BSD-3-Clause
# ---------------------------------------------------------------

add_required_file ${basedir}/data/rrtmg_lw.nc           ./
add_link_file     ${basedir}/data/rrtmg_sw.nc           ./
add_required_file ${basedir}/data/ECHAM6_CldOptProps.nc ./

# APE BCs
if [ x$ozon_file != "x" ] ;  then
  add_required_file ${icon_data_rootFolder}/external/ape_ozone/$ozon_file ./o3_icon_DOM01.nc
else
  add_required_file ${icon_data_rootFolder}/external/ape_ozone/ape_o3_R2B04_1Pa_spr0.90-cell.nc ./o3_icon_DOM01.nc
fi

# vertical grid
if [[ $atmo_model_equations = 3 ]] ; then
  add_required_file ${basedir}/vertical_coord_tables/atm_hyb_sz_${nlev} ./
else
  add_required_file ${basedir}/vertical_coord_tables/atm_hyb_sp_${nlev} ./
fi

#-----------------------------------------------------------------------------
