#! /usr/bin/env python3

# ICON
#
# ------------------------------------------
# Copyright (C) 2004-2024, DWD, MPI-M, DKRZ, KIT, ETH, MeteoSwiss
# Contact information: icon-model.org
# See AUTHORS.TXT for a list of authors
# See LICENSES/ for license information
# SPDX-License-Identifier: BSD-3-Clause
# ------------------------------------------

# -*- coding: utf-8 -*-
#==============================================================================
# create an experiment list
#==============================================================================
from buildbot_config import BuildbotConfig
from icon_paths import buildbot_list_path

from pathlib import Path
import pickle
import click

@click.command()
@click.argument("machine_name", type=str)
@click.option("--queue", type=str, help="the batch system queue where jobs are submitted to")
@click.option("--list", "list_name", type=str, help="the list")
def addmachine(machine_name, queue, list_name):

    full_list_name = buildbot_list_path / list_name

    print(full_list_name)

    if Path(full_list_name).exists():
        thisList = BuildbotConfig.from_pickle(full_list_name)
    else:
        print("did not find experiment list {}".format(full_list_name))
        print("creating new experiment list.")
        thisList = BuildbotConfig()

    thisList.add_machine(machine_name, queue=queue)

    thisList.to_pickle(full_list_name)

if __name__ == "__main__":
    addmachine()
