#!/bin/bash

# ICON
#
# ------------------------------------------
# Copyright (C) 2004-2024, DWD, MPI-M, DKRZ, KIT, ETH, MeteoSwiss
# Contact information: icon-model.org
# See AUTHORS.TXT for a list of authors
# See LICENSES/ for license information
# SPDX-License-Identifier: BSD-3-Clause
# ------------------------------------------

addexp="./addexp"
#############################################################################
##
## create icon-dev list
##
#############################################################################
listname=nwp
./rmlist $listname
./create_all_builders $listname


#-----------------------------------------------------------
# tests for nwp
$addexp exp.test_nwp_R02B04N06multi  exp.test_nwp_R02B04_R02B05_nest  --without-configureflags without-mpi --runflags "cpu_time=00:30:00" --list $listname
# this experiment runs only on mistral with-mpi and without openmp
$addexp exp.test_nwp_R02B04N06multi2  --without-configureflags without-mpi with-openmp --runflags "cpu_time=00:30:00" --list $listname
# set all builders to NWP
./set_builder_flags NWP --builders "*" --list $listname
# deactivate special builders
./set_builder_flags Inactive --builders MISTRAL_ocean --list $listname

#-----------------------------------------------------------
#lets see the list
./lslist $listname

#commit the list
# svn add experiment_lists/$listname
# svn commit experiment_lists/$listname -m "[buildbot_scripts] update $listname"
