#!/bin/bash

# ICON
#
# ------------------------------------------
# Copyright (C) 2004-2024, DWD, MPI-M, DKRZ, KIT, ETH, MeteoSwiss
# Contact information: icon-model.org
# See AUTHORS.TXT for a list of authors
# See LICENSES/ for license information
# SPDX-License-Identifier: BSD-3-Clause
# ------------------------------------------

addexp="./addexp"
#############################################################################
##
## create icon-dev list
##
#############################################################################
listname=test_hamocc
./rmlist $listname
# ./mklist $listname
./create_all_builders $listname

#-----------------------------------------------------------
# add omip technical tests only with mpi parallelization
$addexp  checksuite.ocean_internal/hamocc/exp.test_hamocc_omip_technical \
 --machines mistral --without-configureflags without-mpi enable-mixed --runflags "cpu_time=00:30:00 mpi_procs_pernode=5"  --list $listname

#----------------------------------------------------------- 
#lets see the list
./lslist $listname
#-----------------------------------------------------------

