#!/bin/bash

# ICON
#
# ------------------------------------------
# Copyright (C) 2004-2024, DWD, MPI-M, DKRZ, KIT, ETH, MeteoSwiss
# Contact information: icon-model.org
# See AUTHORS.TXT for a list of authors
# See LICENSES/ for license information
# SPDX-License-Identifier: BSD-3-Clause
# ------------------------------------------

addexp="./addexp"
#############################################################################
##
## create ruby0 list
##
#############################################################################
listname=ruby0
./rmlist $listname
# ./mklist $listname
./create_all_builders $listname

#-----------------------------------------------------------
$addexp exp.esm_bb_ruby0 --without-configureflags without-mpi --machines mistral --runflags "cpu_time=00:10:00 no_of_nodes=4" --list $listname
#./rmexp exp.esm_bb_ruby0 --builders MISTRAL_nag MISTRAL_gcc --list $listname
#-----------------------------------------------------------

#lets see the list
./lslist $listname
#-----------------------------------------------------------

