#!/bin/bash

# ICON
#
# ------------------------------------------
# Copyright (C) 2004-2024, DWD, MPI-M, DKRZ, KIT, ETH, MeteoSwiss
# Contact information: icon-model.org
# See AUTHORS.TXT for a list of authors
# See LICENSES/ for license information
# SPDX-License-Identifier: BSD-3-Clause
# ------------------------------------------

#############################################################################
##
## create build_only list
##
#############################################################################
listname=build_only
./rmlist $listname
./create_all_builders $listname
./set_builder_flags build_only --builders "$(./lslist $listname --builders-only)" --list $listname

./lslist $listname
#############################################################################
