#!/bin/bash

# ICON
#
# ------------------------------------------
# Copyright (C) 2004-2024, DWD, MPI-M, DKRZ, KIT, ETH, MeteoSwiss
# Contact information: icon-model.org
# See AUTHORS.TXT for a list of authors
# See LICENSES/ for license information
# SPDX-License-Identifier: BSD-3-Clause
# ------------------------------------------

addexp="./addexp"
#############################################################################
listname=debug1
./rmlist $listname

./create_all_builders $listname

# deactivate all builders
./set_builder_flags Inactive --builders "$(./lslist $listname --builders-only)" --list $listname

myBuilder='levante_nag_serial'
./set_builder_flags Active --builders $myBuilder --list $listname
./addexp checksuite.infrastructure/buildbot/exp.failed_experiment --builders $myBuilder --list $listname
./addexp checksuite.infrastructure/buildbot/exp.failed_in_subshell --builders $myBuilder --list $listname
./addexp checksuite.infrastructure/buildbot/exp.failed_in_srun --builders $myBuilder --list $listname

./lslist $listname
