#!/bin/bash

# ICON
#
# ------------------------------------------
# Copyright (C) 2004-2024, DWD, MPI-M, DKRZ, KIT, ETH, MeteoSwiss
# Contact information: icon-model.org
# See AUTHORS.TXT for a list of authors
# See LICENSES/ for license information
# SPDX-License-Identifier: BSD-3-Clause
# ------------------------------------------

cd $(dirname "${BASH_SOURCE[0]}")

listname=update-ref
./rmlist $listname
./create_all_builders $listname

./list_part_update-ref $listname

./lslist $listname
