#!/bin/bash

# ICON
#
# ------------------------------------------
# Copyright (C) 2004-2024, DWD, MPI-M, DKRZ, KIT, ETH, MeteoSwiss
# Contact information: icon-model.org
# See AUTHORS.TXT for a list of authors
# See LICENSES/ for license information
# SPDX-License-Identifier: BSD-3-Clause
# ------------------------------------------

set -euo pipefail

cd $(dirname "${BASH_SOURCE[0]}")

listname=tolerance-update
./rmlist $listname
./create_all_builders $listname

# Disable Levante builders that are not in use
./set_builder_flags Inactive --builders "levante_aurora" --list $listname
./set_builder_flags Inactive --builders "levante_gpu_validation" --list $listname
./set_builder_flags Inactive --builders "levante_nag" --list $listname
./set_builder_flags Inactive --builders "levante_nag_serial" --list $listname
./set_builder_flags Inactive --builders "levante_gcc" --list $listname
./set_builder_flags Inactive --builders "levante_gcc_hybrid" --list $listname
./set_builder_flags Inactive --builders "levante_intel" --list $listname
./set_builder_flags Inactive --builders "levante_intel_pio" --list $listname
./set_builder_flags Inactive --builders "levante_intel_hybrid" --list $listname
./set_builder_flags Inactive --builders "levante_intel_hybrid_mixed" --list $listname

./list_part_update-ref $listname

# Set builders inactive, which were used for list_part_update-ref but not for probtest
./set_builder_flags Inactive --builders "levante_cpu_nvhpc" --list $listname
./set_builder_flags Inactive --builders "levante_gpu_nvhpc" --list $listname
# New tolerances needed for atm_qubicc_nc_test.
# In case tolerances are needed for more test cases, please add in the same way.
./list_probtest $listname atm_qubicc_nc_test
# Set builders active, which were used for list_part_update-ref but not for probtest
./set_builder_flags Active --builders "levante_cpu_nvhpc" --list $listname
./set_builder_flags Active --builders "levante_gpu_nvhpc" --list $listname

./lslist $listname
