#!/bin/bash

# ICON
#
# ------------------------------------------
# Copyright (C) 2004-2024, DWD, MPI-M, DKRZ, KIT, ETH, MeteoSwiss
# Contact information: icon-model.org
# See AUTHORS.TXT for a list of authors
# See LICENSES/ for license information
# SPDX-License-Identifier: BSD-3-Clause
# ------------------------------------------

# abort on error
set -euo pipefail

cd $(dirname "${BASH_SOURCE[0]}")
set -x
# create all builders for a given list
listname=$1
if [ x$listname == x ]; then
  echo "Builbot list name missing"
  exit 1
fi

./create_all_builders $listname

./set_builder_flags Inactive --builders "DWD_nec DWD_nec_hybrid DWD_nec_yac2" --list $listname
./set_builder_flags Inactive --builders "levante_intel_hybrid_mixed levante_nag_serial levante_intel_pio levante_cpu_nvhpc levante_gpu_nvhpc" --list $listname
./set_builder_flags Inactive --builders "breeze_gcc breeze_gcc_openmp breeze_intel breeze_intel_openmp breeze_nag" --list $listname
