#! /usr/bin/env python3

# ICON
#
# ------------------------------------------
# Copyright (C) 2004-2024, DWD, MPI-M, DKRZ, KIT, ETH, MeteoSwiss
# Contact information: icon-model.org
# See AUTHORS.TXT for a list of authors
# See LICENSES/ for license information
# SPDX-License-Identifier: BSD-3-Clause
# ------------------------------------------

# -*- coding: utf-8 -*-
#==============================================================================
# create an experiment list
#==============================================================================
from buildbot_config import BuildbotConfig
from icon_paths import buildbot_list_path

from pathlib import Path
import pickle
import click
import sys

@click.command()
@click.argument("name", type=str)
@click.option("--builders-only","builders_only", is_flag=True, show_default=False, default=False, help="list only the builders of a list", required=False)
def lslist(name,builders_only):

    full_list_name = buildbot_list_path / name

    if Path(full_list_name).exists():
      thisList = BuildbotConfig.from_pickle(full_list_name)
    else:
      print("did not find experiment list {}".format(full_list_name))
      sys.exit(1)

    if builders_only:
      print(thisList.list_builders())
    else:
      print(thisList.to_string())

if __name__ == "__main__":
    lslist()
