#! /usr/bin/env python3

# ICON
#
# ------------------------------------------
# Copyright (C) 2004-2024, DWD, MPI-M, DKRZ, KIT, ETH, MeteoSwiss
# Contact information: icon-model.org
# See AUTHORS.TXT for a list of authors
# See LICENSES/ for license information
# SPDX-License-Identifier: BSD-3-Clause
# ------------------------------------------

# -*- coding: utf-8 -*-
#==============================================================================
# delete an experiment lists
#==============================================================================
from buildbot_config import BuildbotConfig
from icon_paths import buildbot_list_path

from pathlib import Path
import pickle
import click
import sys

@click.command()
@click.argument("name", type=str)
def rmlist(name):

    full_list_name = buildbot_list_path / name

    if Path(full_list_name).exists():
        print("Experiment list "+name+" is deleted.")
        full_list_name.unlink()
    else:
        print("did not find experiment list {}. Doing nothing".format(full_list_name))


if __name__ == "__main__":
    rmlist()