#!/bin/bash

# ICON
#
# ------------------------------------------
# Copyright (C) 2004-2024, DWD, MPI-M, DKRZ, KIT, ETH, MeteoSwiss
# Contact information: icon-model.org
# See AUTHORS.TXT for a list of authors
# See LICENSES/ for license information
# SPDX-License-Identifier: BSD-3-Clause
# ------------------------------------------

set -x

case $(echo ${BB_SYSTEM} | tr '[:upper:]' '[:lower:]') in
  nec)
    # Temporary workaound for NEC@DWD:
    # load temporary python virtual environment
    . /hpc/sw/buildbot/home/fe13/venv_dwd0_rh8/bin/activate
    ;;
esac

pwd

python ./scripts/buildbot_scripts/runexp.py
