#! /usr/bin/env python3

# ICON
#
# ------------------------------------------
# Copyright (C) 2004-2024, DWD, MPI-M, DKRZ, KIT, ETH, MeteoSwiss
# Contact information: icon-model.org
# See AUTHORS.TXT for a list of authors
# See LICENSES/ for license information
# SPDX-License-Identifier: BSD-3-Clause
# ------------------------------------------

# -*- coding: utf-8 -*-
#==============================================================================
# create an experiment list
#==============================================================================
from buildbot_config import BuildbotConfig
from util import WhitespaceSeperatedList
from icon_paths import buildbot_list_path

from pathlib import Path
import click
import sys

@click.command()
@click.argument("flags", type=click.Choice(["Active", "Inactive", "build_only"]))
@click.option("--builders", type=WhitespaceSeperatedList(), help="names of the builders to modify", required=True)
@click.option("--list", "list_name", type=str, help="the buildbot configuration list", required=True)
def set_builder_flag(flags, builders, list_name):

    full_list_name = buildbot_list_path / list_name

    if Path(full_list_name).exists():
      thisList = BuildbotConfig.from_pickle(full_list_name)
    else:
      print("did not find experiment list {}".format(full_list_name))
      sys.exit(1)

    thisList.set_builder_flag(builders, flags)

    thisList.to_pickle(full_list_name)

if __name__ == "__main__":
    set_builder_flag()


