#! /bin/sh
#
# Remove experiment setups using config information.
#
# $Id$
#

PROGRAM=`basename $0`
BINDIR=`dirname $0`
PATH="$BINDIR:$PATH"

PYTHONIOENCODING=$(locale -c charmap | tail -1)
export PYTHONIOENCODING

die () {
    echo "$@" >&2
    exit 1
}

[ "x$1" = x ] && die "Oops: invalid number of parameters
Usage: $PROGRAM config_file [key=value...]"

CONFIG=$1
shift

eval `getexp -v "$CONFIG" "$@" || echo '
' exit $?`

ask_and_remove () {
    label="$1"
    dir="$2"
    if [ -d "$dir" ]
    then
        echo "Info for ${EXP_ID}'s $label directory:"
        ( cd "$dir" && du -h --time )
        echo -n "$PROGRAM: remove ${EXP_ID}'s $label directory and its contents [no]? " >&2
        read answer
        case "$answer" in
        y*|Y*)
            rm -r "$dir" && echo "$PROGRAM: removed '$dir'" >&2
            dir=`dirname "$dir"`
            while rmdir "$dir" 2> /dev/null
            do
                echo "$PROGRAM: removed '$dir'" >&2
                dir=`dirname "$dir"`
            done
            ;;
        esac
    fi
}

ask_and_remove working $WORK_DIR
ask_and_remove restart $RESTART_DIR
ask_and_remove script $SCRIPT_DIR
ask_and_remove log $LOG_DIR
ask_and_remove data $DATA_DIR
ask_and_remove monitoring $MON_DIR/$EXP_ID
### $MON_DIR/index.html
